<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="9147" started-at="2018-01-07T15:42:15Z" finished-at="2018-01-07T15:42:24Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.AdidasTask.cucumber.AdidasQATaskRunner@f6c48ac]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Default test" duration-ms="9147" started-at="2018-01-07T15:42:15Z" finished-at="2018-01-07T15:42:24Z">
      <class name="com.AdidasTask.cucumber.AdidasQATaskRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.AdidasTask.cucumber.AdidasQATaskRunner@f6c48ac]" name="setUpClass" is-config="true" duration-ms="351" started-at="2018-01-07T21:12:15Z" finished-at="2018-01-07T21:12:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.AdidasTask.cucumber.AdidasQATaskRunner@f6c48ac]" name="feature" duration-ms="7936" started-at="2018-01-07T21:12:16Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-01-07T21:12:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Testing different requests on the Adidas API]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: analytics_name occurence in each component should be 1 expected [4] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: analytics_name occurence in each component should be 1 expected [4] but found [2]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.lang.AssertionError: analytics_name occurence in each component should be 1 expected [4] but found [2]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:388)
	at com.AdidasTask.cucumber.methods.AdidasTaskMethods.Check_Analytics_Data(AdidasTaskMethods.java:192)
	at com.AdidasTask.cucumber.steps.AdidasQATaskSteps.component_has_analyAcs_data_analytics_name_in_it(AdidasQATaskSteps.java:41)
	at âœ½.Then component has analyAcs data: analytics_name in it(AdidasTask.feature:17)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.AdidasTask.cucumber.AdidasQATaskRunner@f6c48ac]" name="teardown" is-config="true" duration-ms="53" started-at="2018-01-07T21:12:24Z" finished-at="2018-01-07T21:12:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.AdidasTask.cucumber.AdidasQATaskRunner@f6c48ac]" name="tearDownClass" is-config="true" duration-ms="611" started-at="2018-01-07T21:12:24Z" finished-at="2018-01-07T21:12:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.AdidasTask.cucumber.AdidasQATaskRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
